config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :dogs
  resources :likes, only: [:create, :destroy]
  root to: "dogs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :owner, class_name: :User, foreign_key: :user_id
  has_many :likes
  has_many_attached :images
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :dog
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :dogs
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  require "will_paginate/array"
  
  before_action :set_dog, only: [:show, :edit, :update, :destroy]
  before_action :verify_owner, only: [:edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index
    start = Time.now
    if params[:sort] && params[:sort] == "likes_last_hour"
      query = 
        "SELECT * FROM dogs
        LEFT JOIN (
        SELECT likes.dog_id, COUNT(*) AS count FROM likes
        WHERE likes.created_at > date('now', '-1 hour')
        GROUP BY likes.dog_id
        )
        AS likes_last_hour ON dogs.id = likes_last_hour.dog_id
        ORDER BY likes_last_hour.count DESC"
        
      @dogs = Dog.find_by_sql(query)
      # @dogs = Dog.all.sort_by { |dog| dog.likes.where(created_at: 1.hour.ago..Time.now).count }
      # .reverse
    else
      @dogs = Dog.all
    end
    @dogs = @dogs.paginate(page: params[:page], per_page: 5)
    finish = Time.now
    print "Hey! It took #{finish - start} seconds to run this query"

    # With SQL on 10 dogs, operation takes 0.005423 seconds
    # With sort_by on 10 dogs, operation takes 0.004679 seconds
    # With SQL on 10,000 dogs, operation takes 0.003428 seconds
    # With sort_by on 10,000 dogs, operation takes 0.006565 seconds
    # SQL is 86% as fast when the table is small and 190% as fast when the table is large
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
    @likeable = current_user && Like.where(user_id: current_user.id, dog_id: @dog.id).blank?
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        @dog.images.attach(params[:dog][:image]) if params[:dog][:image].present?

        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        @dog.images.attach(params[:dog][:image]) if params[:dog][:image].present?

        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_dog
    @dog = Dog.find(params[:id])
  end

  def verify_owner
    unless current_user == @dog.owner
      redirect_to @dog, notice: "You are not this pup's owner. Please do not try to change or delete pups that are not yours."
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def dog_params
    params.require(:dog).permit(:name, :description, :user_id, :images => [])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :verify_not_owner, only: [:create]

  def create
    @like = Like.new(like_params)

    unless @like.save
      render json: @like.errors, status: :unprocessable_entity
    end
  end

  private

  def verify_not_owner
    @dog = Dog.find(params[:like][:dog_id])
    if current_user.id == @dog.user_id
      redirect_to dogs_path
    end
  end

  def like_params
    params.require(:like).permit(:id, :user_id, :dog_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/_form.html.erb
<%= simple_form_for @dog do |f| %>
  <%= f.input :name %>
  <%= f.input :description, as: :text %>
  <%= f.input :images, input_html: { multiple: true } %>
  <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>

  <% if @dog.images.any? %>
    <%= image_tag @dog.images.first %>
  <% end %>

  <%= f.button :submit %>
<% end %>

app/views/dogs/_thumbnail.html.erb
<a href="<%= url_for(dog) %>">
  <article>
    <h2 class="dog-name"><%= dog.name %></h2>
    <%= image_tag url_for(dog.images.first), class: "dog-photo", alt: "Photo of #{dog.name}" %>
  </article>
</a>

app/views/dogs/edit.html.erb
<h1>Edit Your Dog</h1>
<%= render partial: 'form' %>

app/views/dogs/index.html.erb
<%= form_with(url: dogs_path, method: :get, local: true) do |f| %>
  <%= f.select :sort, [["Default", "default"], ["Most likes in the last hour", "likes_last_hour"]], selected: params[:sort] %>
<%= f.submit "Sort" %>
<% end %>
<% @dogs.each_with_index do |dog, index| %>
  <%= render "dogs/thumbnail", dog: dog %>
  <% if index % 2 != 0 %>
    <%= image_tag("ad.jpg", alt: "Advertisement") %>
  <% end %>
<% end %>
<%= will_paginate @dogs %>

app/views/dogs/new.html.erb
<h1>Add Your Dog</h1>
<%= render partial: 'form' %>

app/views/dogs/show.html.erb
<section>
  <h2><%= @dog.name %></h2>

  <% @dog.images.each do |image| %>
    <%= image_tag url_for(image), alt: "Photo of #{@dog.name}" %>
  <% end %>

  <p><%= @dog.description %></p>

  <% if @dog.likes.count == 0 %>
    <p>No one has liked this pup yet. :-(</p>
  <% elsif @dog.likes.count == 1 %>
    <p>One person likes this pup.</p>
  <% else %>
    <p><%= @dog.likes.count %>people like this pup.</p>
  <% end %>

  <% if current_user && current_user.id == @dog.user_id %>
    <%= link_to "Edit #{@dog.name}'s Profile", edit_dog_path %>
    <br>
    <%= link_to "Delete #{@dog.name}'s Profile", dog_path, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% else %>
    
    <% if @likeable %>
      <%= simple_form_for Like.new do |f| %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.hidden_field :dog_id, value: @dog.id %>
        <%= f.submit 'Like this pup' %>
      <% end %>
    <% end %>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogProfile</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <div id="layout">
      <header>
        <h1><%= link_to 'Dog Profile Demo', root_path %></h1>
        <div class="actions">
          <% if current_user %>
            <%= link_to 'Add your dog', new_dog_path %>
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to 'Sign in', new_user_session_path %>
            <%= link_to 'Sign up', new_user_registration_path %>
          <% end %>
        </div>
      </header>
      <div id="main">
        <div class="notifications">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>
        <%= yield %>
      </div>
      <div class="footer"></div>
    </div>

  </body>
</html>